export const Events = {
  DEBUG_LAUNCH_WAVE: "debug/launch-wave",
  SHOP_PURCHASE_UNIT: "shop/purchase-unit",
  DIFFICULTY_SELECT: "difficulty/select",
  UI_WAVE: "ui/wave",
  UI_RESOURCES: "ui/resources",
  UI_SHOP_CATALOG: "ui/shop-catalog",
  UI_SHOP_STATE: "ui/shop-state",
  UI_SHOP_RESULT: "ui/shop-result",
  UI_DEBUG_STATUS: "ui/debug-status",
  UI_DEBUG_ZOOM: "ui/debug-zoom",
  UI_DIFFICULTY: "ui/difficulty",
  CAMERA_FLY_TO: "camera/fly-to",
  CAMERA_FLY_TO_PRESET: "camera/fly-to-preset",
  UI_WAVE_PROGRESS: "ui/wave-progress",
};
